services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: notes-app

    working_dir: /var/www

    ports:
      - "8000:8000"

    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    extra_hosts:
      - "host.docker.internal:host-gateway"